config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/resource-catalogue-ui-eosc:
      branch: master
      repo: https://github.com/madgeek-arc/resource-catalogue-ui-eosc.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-burgundy-crab.sh
        container: qc.acc_trippy-chartreuse-termite
  QC.Doc:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-amaranth-duck.sh
        container: qc.doc_craggy-myrtle-cat
      github.com/madgeek-arc/resource-catalogue-ui-eosc git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-booby.sh
        container: qc.doc_seedy-beige-tuatara
      github.com/madgeek-arc/resource-catalogue-ui-eosc markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-razzmatazz-barnacle.sh
        container: qc.doc_blurry-chestnut-fly
  QC.Lic:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-malachite-alligator.sh
        container: qc.lic_breezy-tomato-stoat
  QC.Sty:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wisteria-oyster.sh
        container: qc.sty_snoopy-dandelion-shrew
      github.com/madgeek-arc/resource-catalogue-ui-eosc jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-platinum-wrasse.sh
        container: qc.sty_leaky-thistle-jaguar
  QC.Ver:
    repos:
      github.com/madgeek-arc/resource-catalogue-ui-eosc get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-aqua-whale.sh
        container: qc.ver_sloppy-myrtle-badger
timeout: 5400
